### PR TITLE
Added hmac authenticator in list

### PR DESCRIPTION
**Pull request by abhismvit**

### CODE REVIEW

**Comment by abhismvit** [comment]
Added hmac authenticator in package list

**Comment by betatim** [comment]
Hi,

thanks for creating this PR. Could you explain why this change is needed?

**Comment by consideRatio** [comment]
@abhismvit :heart: thank you for catching this and submitting a PR with a fix! 

I have not used or learned about the [hmacauthenticator](https://github.com/yuvipanda/jupyterhub-hmacauthenticator) until now, but remember it in our repo somewhere and indeed I found the following parts in our jupyterhub_config.py, so I figure it makes sense to also install the authenticator in the hub image.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/e0d5c3ec51758f449cf5d0ac752681e1981c18f4/images/hub/jupyterhub_config.py#L303-L305

LGTM

**Comment by abhismvit** [comment]
This PR i  created to add hmac package installation in hub pod.

**Comment by consideRatio** [comment]
Thanks @abhismvit !

**Pull request merged**
