### PR TITLE
update instructions for spinning down aws resources

### PR DESCRIPTION
**Pull request by oneklc**
Was unable to use the CloudFormation page above to delete resources (nothing was there to delete, yes region was correct) 
Terminating resources from ec2 console causes resources to be re-spawned.
Only wan to remove was to run `kops delete cluster`

### CODE REVIEW

**Comment by choldgraf** [comment]
hey @oneklc - thanks for pointing this out!

@cam72cam do you have any thoughts on this? It seems the cloudformation page may not always be a way to delete the k8s cluster.

I can take a pass to clean up the wording a bit, but wanna make sure we have the right information in there first.

**Comment by cam72cam** [comment]
This looks like the right way to go, I did not know that this page existed when I updated the AWS docs.

Perhaps a note on how to do this if you loose your CI node would be helpful as well.
You can do this from any instance with kops installed as long as you do the same exports (NAME, KOPS_STATE_STORE)

**Comment by oneklc** [comment]
Actually i had this issue as i spun down the ci host before realizing i needed it to delete the cluster. Had a tuff time getting back in cause i lost the private key when i terminated ci host.  Luckily i was able to get to the bastion host (cause it respawned) after some monkey work with aws (security and external ip), then set up kops again. Awscli was also need to be set up and configured. 

Thanks for the great documentation. Feel free to reword. Im no english major :)

**Comment by willingc** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/707#issuecomment-396407004

Thanks!

**Comment by willingc** [comment]
Congrats @oneklc for your first contribution to this repo too :tada:

**Pull request merged**
