### PR TITLE
Only activate the Google Container Engine API

### PR DESCRIPTION
**Pull request by yuvipanda**
This now recursively enables the Compute Engine API & the
container registry API

### CODE REVIEW

**Comment by choldgraf** [comment]
nice. we could add a single gif that shows the buttons to click. WDYT?

**Comment by choldgraf** [comment]
ah nvm it seems like the link takes you to the button to enable it

**Comment by choldgraf** [comment]
LGTM

**Comment by willingc** [comment]
Thanks @yuvipanda for the PR and @choldgraf for the review.

**Pull request merged**
