### PR TITLE
Refresh README.md

### PR DESCRIPTION
**Pull request by consideRatio**
I felt the README.md were in need of some attention.

### CODE REVIEW

**Comment by choldgraf** [comment]
really nice! Only one comment (I think that "chart" is a bit too generic so added "helm" back in there). What do you think?

**Comment by consideRatio** [comment]
Excellent I agree @choldgraf ! Is the image okay to use? I picked it from a slide deck without proper understanding of its origin.

**Comment by choldgraf** [comment]
Fine w/ me, I'm +1 on merge - let's leave it open a day or two so others can chime in since it's a relatively prominent file

**Comment by choldgraf** [comment]
🚀 thanks @consideRatio !!!

**Pull request merged**
