### PR TITLE
Update authentication.rst

### PR DESCRIPTION
**Pull request by prkriz**
Overcoming [Caveats while setting up CILogon OAuthAuthenticator for JupyterHub](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/cilogon.py)

### CODE REVIEW

**Comment by choldgraf** [comment]
Thanks very much for the docs PR! I agree this is often a point of confusion for some people. I wonder if it'd be better to just link out to the oauthenticator docs where this issue is addressed (and if it isn't, we should add it to the docs there).

@minrk do you know if this issue is mentioned in oauthenticator? Currently it seems to exist only in the docstring of that module...

**Comment by minrk** [comment]
It is mentioned [in oauthenticator](https://github.com/jupyterhub/oauthenticator/blob/75d8b9b5ee366e7094d28a4c569986f04e3ea802/oauthenticator/cilogon.py#L10), but could be more prominent. Thanks for the PR!

**Comment by consideRatio** [comment]
Thank you @prkriz !!! :D :heart:

**Comment by prkriz** [comment]
Happy to contribute!! :)

**Comment by choldgraf** [comment]
wooo thanks!

**Pull request merged**
