### PR TITLE
Add note about ingress workaround.

### PR DESCRIPTION
**Pull request by ryanlovett**
This might be more suitable for general troubleshooting section of z2jh as opposed to a release-specific issue. But since the upstream issue coincides with this particular release it is probably fine to put it here.

### CODE REVIEW

**Comment by yuvipanda** [comment]
I think this should be somewhere else, since it can possibly happen to any object, including some that you should not delete (PVC, for example).

**Comment by choldgraf** [comment]
@yuvipanda any suggestions on where? (more generally, I like the idea of being able to incorporate user feedback about upgrade struggles into the docs)

**Comment by choldgraf** [comment]
also @ryanlovett just a note that I made a commit directly to your PR :-)

**Comment by yuvipanda** [comment]
I think a more general troubleshooting section?

But if you think it's ok where it is I'll defer to you, especially since it' tied to a specific helm bug. If this keeps happening for other objects and people report it we can add them here I guess.

**Comment by choldgraf** [comment]
my thinking is "one report, treat it as an exception and make a one-off doc fix, > 1 report, treat it as a more general problem and consider building general docs around it"

**Comment by yuvipanda** [comment]
+1, @choldgraf :) Thanks for the report, @ryanlovett

**Pull request merged**
