### PR TITLE
Add contributors.py tool to generate list of contributors

### PR DESCRIPTION
**Pull request by yuvipanda**
This needs:

- Docs on how to run this
- Docs on how to find the dates for the various repos involved

### CODE REVIEW

**Comment by yuvipanda** [comment]
I think for this release, we only need:

1. z2jh dates are between last tag and this one
2. no need for helm-chart, since that repo has been deprecated and unused
3. JupyterHub and OAuthenticator we haven't bumped
4. KubeSpawner between the tagged releases.

**Comment by yuvipanda** [comment]
I updated them for v0.6

**Comment by yuvipanda** [comment]
I found these dates by:

1. Looking at the date for last tag of z2jh, and then the latest commit 
2. Looking for the tag of kubespawner used in last version of z2jh, and the tag in current version

This could ofc be automated more, but it currently falls below my personal 'is it going to be more time automating than doing?' time cutoff :D

**Comment by yuvipanda** [comment]
I also just generated the list to test, feel free to just use this:

```
[Aaron Culich](https://github.com/aculich)
[Anirudh Ramanathan](https://github.com/foxish)
[Antoine Dao](https://github.com/twanito)
[BerserkerTroll](https://github.com/BerserkerTroll)
[Carol Willing](https://github.com/willingc)
[Chris Holdgraf](https://github.com/choldgraf)
[Christian Mesh](https://github.com/cam72cam)
[Erik Sundell](https://github.com/consideRatio)
[forbxy](https://github.com/forbxy)
[Graham Dumpleton](https://github.com/GrahamDumpleton)
[gweis](https://github.com/gweis)
[Ian Allison](https://github.com/ianabc)
[Jason Kuruzovich](https://github.com/jkuruzovich)
[Jesse Kinkead](https://github.com/jkinkead)
[madanam1](https://github.com/madanam1)
[Matthew Rocklin](https://github.com/mrocklin)
[Matthias Bussonnier](https://github.com/Carreau)
[Min RK](https://github.com/minrk)
[Ryan Lovett](https://github.com/ryanlovett)
[Simon Li](https://github.com/manics)
[Steve Buckingham](https://github.com/stevebuckingham)
[Steven Normore](https://github.com/snormore)
[Tim Head](https://github.com/betatim)
[Yuvi Panda](https://github.com/yuvipanda)
[ZachGlassman](https://github.com/ZachGlassman)
```

It is sorted by [casefolded](https://www.w3.org/International/wiki/Case_folding) names in ascending order :)

**Comment by yuvipanda** [comment]
Added more docs and stuff!

**Comment by choldgraf** [comment]
looks great - I'll add some more docs around this in another PR

**Pull request merged**
