### PR TITLE
Added encryption instructions for AWS deployment

### PR DESCRIPTION
**Pull request by summerswallow-whi**
My RST editing is not quite right. I appreciate comments on how to fix the formatting. I don't have a good previewer outside of git.

### CODE REVIEW

**Comment by choldgraf** [comment]
hey @summerswallow - just a note that someone will get to reviews etc soon, last week was the jupyter team meeting so we were pretty pre-occupied during that time!

**Comment by summerswallow-whi** [comment]
No problem. Just wanted to get this out there so others could benefit if desired.

**Comment by choldgraf** [comment]
seeing if @cam72cam may have a cycle or two to check this out, as I believe they are working with AWS as well. Any chance you could give this a shot? Or if it's not relevant to you that's fine too :-)

**Comment by cam72cam** [comment]
We are primarily using EFS for our full deployments due to concerns about EBS being unable to mount across AZ.  I can set up a temp cluster later today and follow your instructions.

**Comment by cam72cam** [comment]
PR looks good to me, though it may need some format tweaks once it's merged

**Comment by choldgraf** [comment]
I can take a formatting pass :-)

**Comment by summerswallow-whi** [comment]
By default z2jh uses EBS, However, my organization as well as probably others are very interested in using EFS. Documenting how you @cam72cam do it would benefit others.

**Comment by cam72cam** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/421

I'll be adding a doc page or two soon to cover what we are doing.

Maybe we want to add a link to the multiple storage options off of this page instead of adding them all here.

**Comment by willingc** [comment]
Hi folks, I'm going to merge #715, #708, and this PR #707. Thanks all for the work. Once they are all merged, I will open a typo, grammar, and edit PR, which I will ping all of you on for re-review of the technical bits.

**Comment by consideRatio** [comment]
Excellent @willingc !!! :heart:

**Pull request merged**
