### PR TITLE
hub: Switch base image to latest LTS

### PR DESCRIPTION
**Pull request by yuvipanda**
18.04 is a while ago :)

This also brings a newer version of python, I believe

### CODE REVIEW

**Comment by yuvipanda** [comment]
Running dependency freezer didn't seem to make any difference.

**Comment by consideRatio** [comment]
@yuvipanda, @manics initiated this kind of work for the JupyterHub project's Docker image as well. See https://github.com/jupyterhub/jupyterhub/pull/3156.

**Comment by minrk** [comment]
I think we need to remove the pinning of libc-bin, etc. that should only be relevant for the old release

**Comment by yuvipanda** [comment]
Thanks for the fix, @minrk! This LGTM

**Comment by consideRatio** [comment]
Nice! :D

**Pull request merged**
