### PR TITLE
Add changelog for 3.3.8

### PR DESCRIPTION
**Pull request by consideRatio**

### CODE REVIEW

**Comment by manics** [comment]
Shouldn't this be against the 3.x branch? Then we can drop the unreleased changes section.

**Comment by consideRatio** [comment]
We should update the changelog in main and for 3.x, and I mean to cherry-pick this commit into 3.x after merging to mimic what was done for other patch releases. It could be done the other way around as well though.

The unreleased section changes was unrelated to the PR, and I could extract them but I figured was OK to bundle in this.

**Comment by consideRatio** [comment]
@manics thank you for the neat "summarize linkcheck issues" btw!!

image

**Comment by consideRatio** [comment]
Preview:
image

**Comment by manics** [comment]
Looks like we've got unreleased changes in the changelogs for other backported relaseses. Given we need to make this release quickly it's fine for now, but in future I think a changelog (which forms part of a tag) shouldn't containfuture changes.

**Pull request merged**
