### PR TITLE
Add ingress.ingressClassName config option

### LINKED ISSUE #2380: Support configuring ingressClassName
Previously, a user could configure the ingress controller to use by setting an annotation (kubernetes.io/ingress.class) on the ingress resource. Now though. there is a new field under `spec` that should be used instead called `ingressClassName`. This is not yet configurable via our Helm chart and we should make it configurable.

https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

One can still rely on a default ingressClass, one can for example configure the ingress-nginx helm chart like this. Below I provide some other common useful configuration options for running with a z2jh deployment, but only the part about ingressClass is relevant to this issue in practice.

```yaml
controller:
  # To make our Ingress resources able to rely on a default IngressClass,
  # we need to also configure watchIngressWithoutClass.
  ingressClassResource:
    default: true
  watchIngressWithoutClass: true
  
  # Below is additional config relevant to the ingress-nginx Helm chart used
  # to proxy traffix to a JupyterHub Helm chart deployment.

  config:
    # allow POSTs of upto 64MB, to support saving large notebooks.
    proxy-body-size: 64m

  # allow access to the proxy-public service
  podLabels:
    hub.jupyter.org/network-access-proxy-http: "true"
```

### References

- [K8s api reference on Ingress resources about spec.ingressClassName](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1-networking-k8s-io)

### PR DESCRIPTION
**Pull request by consideRatio**
Closes #2380 that contains details about the need for this PR.

### CODE REVIEW

**Comment by consideRatio** [comment]
We are quite low on review capacity, so I did a delayed self-review and will go for a merge now that its validated against a k8s 1.22 api-server thanks to #2404

**Comment by pebabion** [comment]
@consideRatio did you manage to test this? I'm hitting the exact same error.
```

rpc error: code = Unknown desc = `helm template . --name-template jupyterhub --namespace jupyterhub --kube-version 1.22 --values .jupyterhub/values.yaml --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1/Challenge --api-versions acme.cert-manager.io/v1/Order --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1/CustomResourceDefinition --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1/APIService --api-versions apps/v1 --api-versions apps/v1/ControllerRevision --api-versions apps/v1/DaemonSet --api-versions apps/v1/Deployment --api-versions apps/v1/ReplicaSet --api-versions apps/v1/StatefulSet --api-versions argoproj.io/v1alpha1 --api-versions argoproj.io/v1alpha1/AppProject --api-versions argoproj.io/v1alpha1/Application --api-versions argoproj.io/v1alpha1/ApplicationSet --api-versions argoproj.io/v1alpha1/ClusterWorkflowTemplate --api-versions argoproj.io/v1alpha1/CronWorkflow --api-versions argoproj.io/v1alpha1/Workflow --api-versions argoproj.io/v1alpha1/WorkflowEventBinding --api-versions argoproj.io/v1alpha1/WorkflowTaskResult --api-versions argoproj.io/v1alpha1/WorkflowTaskSet --api-versions argoproj.io/v1alpha1/WorkflowTemplate --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta2 --api-versions autoscaling/v2beta2/HorizontalPodAutoscaler --api-versions batch/v1 --api-versions batch/v1/CronJob --api-versions batch/v1/Job --api-versions batch/v1beta1 --api-versions batch/v1beta1/CronJob --api-versions bitnami.com/v1alpha1 --api-versions bitnami.com/v1alpha1/SealedSecret --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1/Certificate --api-versions cert-manager.io/v1/CertificateRequest --api-versions cert-manager.io/v1/ClusterIssuer --api-versions cert-manager.io/v1/Issuer --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1/CertificateSigningRequest --api-versions cilium.io/v2 --api-versions cilium.io/v2/CiliumClusterwideNetworkPolicy --api-versions cilium.io/v2/CiliumEndpoint --api-versions cilium.io/v2/CiliumExternalWorkload --api-versions cilium.io/v2/CiliumIdentity --api-versions cilium.io/v2/CiliumLocalRedirectPolicy --api-versions cilium.io/v2/CiliumNetworkPolicy --api-versions cilium.io/v2/CiliumNode --api-versions cilium.io/v2alpha1 --api-versions cilium.io/v2alpha1/CiliumEgressNATPolicy --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1/Lease --api-versions datadoghq.com/v1alpha1 --api-versions datadoghq.com/v1alpha1/DatadogMetric --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1/EndpointSlice --api-versions discovery.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1/EndpointSlice --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1/Event --api-versions events.k8s.io/v1beta1 --api-versions events.k8s.io/v1beta1/Event --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta1/PriorityLevelConfiguration --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1/Ingress --api-versions networking.k8s.io/v1/IngressClass --api-versions networking.k8s.io/v1/NetworkPolicy --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1/RuntimeClass --api-versions node.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1/RuntimeClass --api-versions policy/v1 --api-versions policy/v1/PodDisruptionBudget --api-versions policy/v1beta1 --api-versions policy/v1beta1/PodDisruptionBudget --api-versions policy/v1beta1/PodSecurityPolicy --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1/ClusterRole --api-versions rbac.authorization.k8s.io/v1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1/Role --api-versions rbac.authorization.k8s.io/v1/RoleBinding --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1/PriorityClass --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshot --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshotClass --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshotContent --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1/CSIDriver --api-versions storage.k8s.io/v1/CSINode --api-versions storage.k8s.io/v1/StorageClass --api-versions storage.k8s.io/v1/VolumeAttachment --api-versions storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1beta1/CSIStorageCapacity --api-versions v1 --api-versions v1/ConfigMap --api-versions v1/Endpoints --api-versions v1/Event --api-versions v1/LimitRange --api-versions v1/Namespace --api-versions v1/Node --api-versions v1/PersistentVolume --api-versions v1/PersistentVolumeClaim --api-versions v1/Pod --api-versions v1/PodTemplate --api-versions v1/ReplicationController --api-versions v1/ResourceQuota --api-versions v1/Secret --api-versions v1/Service --api-versions v1/ServiceAccount --include-crds` failed exit status 1: Error: values don't meet the specifications of the schema(s) in the following chart(s): jupyterhub: - ingress: Additional property ingressClassName is not allowed
```

**Comment by consideRatio** [comment]
@pebabion when using what version? This is not yet released with a non-prerelease version so you have to explicitly specify for example `--version=2.0.0-beta.1` for now. Working intensively now to get 2.0.0 out

**Comment by pebabion** [comment]
@consideRatio thanks! I figured that `ingressClassName` was not available in `1.2.0`. Thanks! All the best with the new release!

**Pull request merged**
