### PR TITLE
update local install instructions for minikube

### PR DESCRIPTION
**Pull request by willingc**
Closes #551

### CODE REVIEW

**Comment by choldgraf** [comment]
Nice! There was a merge conflict introduced with #554 and this one, so I assumed this took precedence since it had more complete information.

**Comment by manics** [comment]
Shouldn't this be in the `master` branch? It's been merged into https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/willingc-patch-1

**Comment by choldgraf** [comment]
hmm, did it not make it into master in the end? I think it was eventually merged into master here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/551

**Comment by manics** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CONTRIBUTING.md is missing the changes from this PR

**Comment by choldgraf** [comment]
Ah yes! Good catch! I think this just got merged a second ago

**Comment by willingc** [comment]
@choldgraf The merge that happened the other day merged into a branch instead of master.

**Pull request merged**
