### PR TITLE
Rename master branch to main

### PR DESCRIPTION
**Pull request by manics**
This is a copy of the workflow from https://github.com/jupyterhub/jupyterhub/pull/3462
- Replaced `master` with `HEAD` in GitHub URLs, which seems to automatically resolve to the default branch
- Replaced a few other mentions of `master` where it refers to a git branch

Actions to take, in order:
- [x] approve this PR
- [x] rename the default branch to `main` in GitHub repo settings
- [ ] merge this PR
- [ ] check the publish workflow published the expected outputs

---
Remaining mentions of `master`:
```
$ git grep master

CHANGELOG.md:- CI: fix RTD builds on push to master [#1816](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1816) ([@consideRatio](https://github.com/consideRatio))
CHANGELOG.md:- CI: always publish helm chart on push to master [#1765](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1765) ([@consideRatio](https://github.com/consideRatio))
CONTRIBUTING.md:subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'jupyterhub/k8s-hub:0.9-217f798', 'images/hub', '--build-arg', 'JUPYTERHUB_VERSION=git+https://github.com/jupyterhub/jupyterhub@master']' returned non-zero exit status 100.
doc/source/conf.py:# Configuration reference: https://www.sphinx-doc.org/en/master/usage/configuration.html
doc/source/conf.py:# ref: https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
doc/source/conf.py:# ref: https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration
doc/source/conf.py:# The master toctree document.
doc/source/conf.py:master_doc = "index"
doc/source/conf.py:# ref: http://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder
doc/source/conf.py:# ref: http://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
doc/source/jupyterhub/customizing/user-environment.md:            "master",
doc/source/jupyterhub/customizing/user-environment.md:This will synchronize the master branch of the repository to a folder called
doc/source/jupyterhub/customizing/user-environment.md:                  gitpuller https://github.com/data-8/materials-fa17 master materials-fa;
doc/source/kubernetes/amazon/efs_storage.md:   Next, create a new security group for NFS traffic (target other instances in that group). Add a rule for incoming NFS traffic to the node security group and to the master security group. Change the EFS volume to use that security group.
doc/source/kubernetes/amazon/efs_storage.md:   To verify that your EFS volume is working correctly, ssh into one of the master nodes and su to root. Next,
doc/source/kubernetes/amazon/step-zero-aws-eks.md:   This is necessary for the workers to find the master plane.
doc/source/kubernetes/amazon/step-zero-aws.md:    --master-size t2.micro \
doc/source/kubernetes/amazon/step-zero-aws.md:    --master-volume-size 10 \
doc/source/kubernetes/amazon/step-zero-aws.md:    This creates a cluster where all of the masters and nodes are in private subnets and don't have external IP addresses. A mis-configured security group or insecure ssh configuration is less likely to compromise the cluster.
doc/source/kubernetes/amazon/step-zero-aws.md:    --master-count
doc/source/kubernetes/amazon/step-zero-aws.md:      Spawns more masters in one or more VPCs
doc/source/kubernetes/amazon/step-zero-aws.md:    --master-zones
doc/source/kubernetes/amazon/step-zero-aws.md:      specify zones to run the master in
doc/source/kubernetes/amazon/step-zero-aws.md:    --master/node-security-groups
doc/source/kubernetes/amazon/step-zero-aws.md:      Allows you to specify additional security groups to put the masters and nodes in by default
doc/source/kubernetes/setup-helm2.md:curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
doc/source/resources/glossary.md:      also referred to as the master, will answer questions and update the
images/image-awaiter/main.go:	flag.StringVar(&caPath, "ca-path", "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt", "Path to CA bundle used to verify kubernetes master")
```
- `CHANGELOG.md` uses `master` in some historical PR descriptions
- `CONTRIBUTING.md` has `master` in some old log output
- `doc/source/kubernetes/setup-helm2.md` is removed in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2216
- `doc/source/jupyterhub/customizing/user-environment.md` uses `master` in a gitpuller command
- The rest are unrelated to git branch names

### CODE REVIEW

**Comment by consideRatio** [comment]
Nice work let's get this done! I'll do review tonight/tomorrow. If this LGTM, can i go ahead and follow the steps you outlined or should i wait a bit?

**Comment by manics** [comment]
It should be good to go (unless I've missed something) 😀

**Review by consideRatio — APPROVED** [review]

**Comment by consideRatio** [comment]
All steps done.
- should we delete the master branch like in jupyterhub
- should we do something with PRs open? Perhaps they retarget or get notified i we delete the master branch?

**Comment by consideRatio** [comment]
Thanks @manics for your maintenance work ❤️❤️❤️

**Comment by manics** [comment]
Oh, I should've said rename the master branch to main (which will automatically update all PRs) instead of creating a new branch. If there's no changes between master/main might be worth deleting main and renaming master?

**Comment by consideRatio** [comment]
@manics ah absolutely! can you go ahead and do some magic?

**Comment by manics** [comment]
I don't have permission to change the default branch back to master (though it looks like I've got permission to rename branches)

**Comment by consideRatio** [comment]
@manics I invited you to be an admin for this repo where I'm an admin already

**Comment by manics** [comment]
Thanks, done! I've left the temporary main branch as `main-to-be-deleted` in case you had anything dependent on it, otherwise you can delete it.

**Comment by consideRatio** [comment]
@manics :tada: wieee nice - main-to-be-deleted branch deleted

**Comment by consideRatio** [comment]
@manics can you updated you checkpoint list with the branch rename step you did so I can use this as a reference for other repos in the org later?

**Comment by manics** [comment]
I opened a new team-compass issue instead: https://github.com/jupyterhub/team-compass/issues/412

**Pull request merged**
