### PR TITLE
Generalize build.py to be not z2jh specific

### PR DESCRIPTION
**Pull request by yuvipanda**
I'm calling it 'chartpress', like a printing press but for charts.

- Factor out repo specific info into a separate chartpress.yaml file,
  so we can move build.py to a separate repo eventually
- Fixup travis to use new commandline params

### CODE REVIEW

**Comment by yuvipanda** [comment]
Next step here is to make sure this works for binderhub's chart CI too, and then split it up into its own repo.

Also perhaps clean up the code :)

**Comment by minrk** [comment]
Anything else you want to do here? e.g. test that it works with binderhub first?

**Comment by yuvipanda** [comment]
I tested the publish_chart bit (which I couldn't on the flight) and fixed it. It's good to go, @minrk. Needs verification post merge tho.

**Comment by minrk** [comment]
`helm package` [failed](https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s/builds/312464887)

**Pull request merged**
