### PR TITLE
Add support for setting default_url in config.yaml

### LINKED ISSUE #375: Allow making JupyterLab default thing to launch
Is there a way to make JupyterLab come up by default when new users connect?

Is there a way to get the JupyterHub control panel from JupyterLab?

### PR DESCRIPTION
**Pull request by yuvipanda**
Also adds docs on how to make JupyterLab be default.

Fixes #375

### CODE REVIEW

**Comment by yuvipanda** [comment]
Feel free to amend the docs! I hope my rst skills are improving :)

**Comment by minrk** [comment]
Another way to launch jupyterlab is to change the cmd from `jupyterhub-singleuser` to `jupyter-labhub`. I wonder if a `jupyterlab` boolean flag and/or exposing the launch command are the best options here?

**Comment by yuvipanda** [comment]
Possibly at some point! But I think we should expose default_url anyway, since people might want to launch into (say) RStudio. It might be useful to have a 'defaultApplication' at some point that can refer to classic, lab, RStudio, nteract (when it launches) etc rather than a jupyterlab: true, but I think that should be a separate patch.

**Comment by choldgraf** [comment]
@yuvipanda is this ready to go from a code perspective? I can take a quick docs pass and then +1 for merge but I won't push to your branch until you give me the green light

**Comment by yuvipanda** [comment]
@choldgraf yep, feel free to push! Code and docs are ready here.

**Comment by choldgraf** [comment]
@yuvipanda a few improvements pushed! I'm +1 on a merge but probably shouldn't since I've now touched the PR.

**Comment by yuvipanda** [comment]
Investigating the build failure, it looks like travis never started the build and timed itself out? Restarted it.

**Comment by minrk** [comment]
Travis is having issues, but approved assuming Travis confirms. Anyone who sees the green check mark show up here should feel free to merge.

**Comment by yuvipanda** [comment]
This is a strange failure, since travis says:

```
The command "./ci/test.sh" exited with 0.
Done. Your build exited with 1.
```

So test success and build fail?

**Comment by yuvipanda** [comment]
Ah, the error is:

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/zesty-security/universe/source/Sources  404  Not Found [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/universe/source/Sources  404  Not Found [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty-updates/universe/source/Sources  404  Not Found [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty-backports/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.162 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends       git       python3       python3-dev       python3-pip       python3-setuptools       libcurl4-openssl-dev       libssl-dev       build-essential       npm       nodejs-legacy       &&     apt-get purge && apt-get clean' returned a non-zero code: 100
Traceback (most recent call last):
  File "./build.py", line 193, in <module>
    main()
  File "./build.py", line 182, in main
    value_mods = build_images(chart['imagePrefix'], chart['images'], args.tag, args.commit_range, args.push)
  File "./build.py", line 78, in build_images
    build_image(image_path, image_spec, build_args)
  File "./build.py", line 51, in build_image
    subprocess.check_call(cmd)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'jupyterhub/k8s-hub:2284ae4', 'images/hub', '--build-arg', 'JUPYTERHUB_VERSION=0.8.1']' returned non-zero exit status 100.
```

which also feels like a Travis issue, since am sure archive.ubuntu.com is still around :)

**Comment by yuvipanda** [comment]
Rebased!

**Comment by choldgraf** [comment]
travis timed out again

**Comment by yuvipanda** [comment]
yeah, this time it's broken in ways that need #419 to fix :)

**Comment by yuvipanda** [comment]
@choldgraf fixed now!

**Pull request merged**
