### PR TITLE
bump various requirements

### LINKED ISSUE #811: Update the hub image requirements.txt
```
statsd==3.2.1
jupyterhub-dummyauthenticator==0.3.1
jupyterhub-tmpauthenticator==0.4
jupyterhub-ltiauthenticator==0.2
nullauthenticator==1.0
pymysql==0.7.11
psycopg2==2.7.3.2
pycurl==7.43.0
mwoauth==0.3.2
globus_sdk[jwt]==1.2.1
oauthenticator==0.7.2
cryptography==2.0.3
https://github.com/jupyterhub/ldapauthenticator/archive/718eb59.tar.gz
https://github.com/consideratio/kubespawner/archive/4273c34.tar.gz
```

I figure we should bumb some of these before release

### PR DESCRIPTION
**Pull request by minrk**
some of these have gotten a bit out of date

in preparing for release of the chart, we should replace all pinned commits with releases

Still awaiting release:

- jupyterhub 0.9.2
- kubespawner 0.9.0

closes #811 #834

### CODE REVIEW

**Comment by consideRatio** [comment]
This build does not start because of failing builds running. This build have a chance to work, as it will update the hub image and have it available. Hmmm.. Something like this.

So, I've cancelled z2jh builds that would end up taking 50min+, I'll have a PR coming to ensure this does not happen again. It is within my #758 currently, and i'll break it apart soon.

**Comment by consideRatio** [comment]
I think there is a batchspawner build with a huge amount of jobs running, so this build is never allowed to start ^^

**Comment by consideRatio** [comment]
Builds passed!!!

**Comment by willingc** [comment]
@consideRatio I'm leaving this for you to merge. It looks good to me.

**Comment by consideRatio** [comment]
Thank you @minrk and @willingc !

**Pull request merged**
