### PR TITLE
CI bump: k8s 1.9.0 / helm 2.9.1 / minikube 0.28.0

### PR DESCRIPTION
**Pull request by consideRatio**
Bumping CI to use latest k8s/helm/minikube.

Currently #758 CI is failing to start because Helm 2.9.1 is required.

- [Minikube changelog](https://github.com/kubernetes/minikube/blob/v0.28.0/CHANGELOG.md)

### CODE REVIEW

**Comment by clkao** [comment]
Is it time to create travis env matrix for multiple versions of k8s?

**Comment by consideRatio** [comment]
@clkao perhaps but I suspect it is overkill because I run with the assumption that kubernetes api-server will behave similarly assuming you using an older API.

The solution to the build error seems to be to upgrade the build system to run on Ubuntu 16.04, but travis doesn't support that and after reading posts I've given up all hope on that is going to happen in a reasonable time.

I noticed that the jupyterhub/jupyterhub repo used CircleCI, something we can use for z2jh as well? I'm clueless about if you are paying for it, or how it would work etc. Anyone with clues about this? @clkao @minrk ?

**Comment by consideRatio** [comment]
How should we go about making minikube execute on Ubuntu 16.04 instead of 14.04 where `systemd` is available and the issues we face above will go away?

**Comment by consideRatio** [comment]
@clkao it could be useful to test 1.9 as well as 1.11, because helm could be smart about certain features by default if we are on k8s 1.11 but shut them down if we are below.

Do you have experience on creating such travis environment matrix?

**Comment by clkao** [comment]
FTR matrix ci is in #762

**Pull request merged**
