### PR TITLE
docs: fix the dynamically set version of chart/jupyterhub

### LINKED ISSUE #1952: Docs: fix our dynamically retrieved chart version
Our landing page has an invalid note about the Helm chart version which we should fix. As you can see from the rST, it [references a custom variable](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blame/master/doc/source/index.rst#L23-L25), which is set through inspection of Chart.yaml.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/ba38491ef41d59af55f1b2510c60bd913116e1b6/doc/source/conf.py#L40-L55

### Screenshot from z2jh.jupyter.org's landing page
image

---

Related to fixing this, it could be nice to pin references in docs currently going to master to instead go to the associated release. See @manics comment here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1943/files#r546444303

### LINKED ISSUE #1958: Mismatched helm chart versions
### Bug description

Versions of helm charts are mismatched on the page that first installs the chart (0.9.0):

https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html

and the page that shows how to upgrade the configuration (0.8.2):

https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/extending-jupyterhub.html

I believe that this can have some rather unfortunate consequences, when trying to upgrade the configuration. 

In particular, I get this error: 

```
➜  kubectl get pod --namespace $NAMESPACE
NAME                     READY   STATUS             RESTARTS   AGE
hub-7f64886954-n8phz     0/1     CrashLoopBackOff   6          11m
proxy-77dfb66845-gg8gl   1/1     Running            0          11m
➜  kubectl logs hub-7f64886954-n8phz     
Loading /etc/jupyterhub/config/values.yaml
Loading /etc/jupyterhub/secret/values.yaml
[I 2020-12-21 22:25:53.684 JupyterHub app:1673] Using Authenticator: oauthenticator.github.GitHubOAuthenticator-0.8.0
[I 2020-12-21 22:25:53.684 JupyterHub app:1673] Using Spawner: kubespawner.spawner.KubeSpawner
[I 2020-12-21 22:25:53.685 JupyterHub app:1016] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2020-12-21 22:25:53.699 JupyterHub dbutil:125] Upgrading sqlite:///jupyterhub.sqlite
[I 2020-12-21 22:25:53.700 JupyterHub dbutil:105] Backing up jupyterhub.sqlite => jupyterhub.sqlite.2020-12-21-222553
[I 2020-12-21 22:25:54.202 alembic.runtime.migration migration:130] Context impl SQLiteImpl.
[I 2020-12-21 22:25:54.203 alembic.runtime.migration migration:137] Will assume non-transactional DDL.
FAILED: Can't locate revision identified by '4dc2d5a8c53c'
[E 2020-12-21 22:25:54.207 alembic.util.messaging messaging:60] Can't locate revision identified by '4dc2d5a8c53c'
[E 2020-12-21 22:25:54.268 JupyterHub app:1958]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1680, in initialize
        self.init_db()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1073, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/dbutil.py", line 130, in upgrade_if_needed
        upgrade(db_url)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/dbutil.py", line 89, in upgrade
        ['alembic', '-c', alembic_ini, 'upgrade', revision]
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['alembic', '-c', '/tmp/tmp3n17twak/alembic.ini', 'upgrade', 'head']' returned non-zero exit status 255.

```

#### Expected behaviour

I think this should be 0.9.0 in both places.

### PR DESCRIPTION
**Pull request by consideRatio**
## Original PR message

This doesn't work all the way yet because we had a version set in a code formatted block, and within it, |my_rst_epilog_variable| wasn't expanded.

@choldgraf do you have a suggestion in this case? We can workaround it by not referencing the version in the code block of course.

Closes #1952, Closes #1958

# Progress update

## Challenge 1 - rst + md
To provide subsitutions in .rst files and .md files.

- For .rst, I can use rst_epilog in conf.py and |my_variable| in the .rst files.
- For .md, I can use myst_substitutions in conf.py and {{my_variable}} in the .md files. To do this, I enable the `substitution` myst extension as well. For more details, see the [extension docs](https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html#substitutions-with-jinja2). This requires the latest myst-parser version 0.13.0

### Resolution
To go all in on MyST and leave rST behind and using `myst_substitions` in conf.py. I'm personally very tired of working against two sets of documentation systems and the rST syntax which I don't know so well by being a Jupyter Notebook and GitHub user. I also would appreciate being able to focus helping out the MyST ecosystem and think that the z2jh projects adoption will lead to doing so as well.

## Challenge 2 - substitutions within a link (or code block etc)
As @manics pointed out, it would be nice to let the docs point to a specific version of JupyterHub or z2jh on GitHub when we use github links. For example, if we want in our docs to reference what is going on in image/hub/requirements.txt, we don't want to direct users to /master but to /a-tag or /a-hash, but substitutions like `[my-link](my-dynamic-url{{ my_var }})` won't work.

### Link workaround
We can use a substitution to be replaced with the entire link, but this only works with `myst_substitutions` and not with `rst_epilog` which emits the following error. It wouldn't be sustainable for code blocks either I think.

```
<rst_epilog>:7: WARNING: Substitution definition contains illegal element <target>:

<target ids="hub-images-requirements-txt" names="hub/images/requirements.txt" refuri="https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f7d7357d/images/hub/requirements.txt">

.. |requirements| replace:: dasd `hub/images/requirements.txt <https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f7d7357d/images/hub/requirements.txt>`_
<rst_epilog>:7: WARNING: Substitution definition contains illegal element <target>:

<target ids="hub-images-requirements-txt" names="hub/images/requirements.txt" refuri="https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f7d7357d/images/hub/requirements.txt">
```

I assume this is for security reasons, in case someone could inject rst_epilog and end up modifying things.

## Final update

I learned about limitations to substitutions, and the rST based and MyST based way of doing things. I ended up transitioning index.rst to index.md with MyST content as required to provide a dynamic link to a pinned version of images/hub/requirements.txt as I simply failed to do it with rST without doing something extensive like for generating the schema file.

### CODE REVIEW

**Comment by choldgraf** [comment]
Heya - just arriving here. I was going to recommend checking out the latest syntax additions for substitution in myst markdown, sounds like you have discovered this already and have a path forward?

**Comment by consideRatio** [comment]
@choldgraf yepp thank you!

I have not figured out a viable solution to having a reference to a conf.py calculated variable within a code block, but other than that things are good as long as I drop .rst. Using .rst, I failed to use rst_epilog and a Replace instruction to add a link, so in practice I needed MyST to link to a pinned version of images/hub/requirements.txt

**Comment by choldgraf** [comment]
@consideRatio a quick thought - @chrisjsewell has been working on a lightweight rST to MyST converter. I think it is ready for testing here: https://github.com/executablebooks/rst-to-myst/

If you want, maybe it'd be useful for these efforts at converting documentation?

**Comment by consideRatio** [comment]
@choldgraf thank you for pointing me to it! I love to see it is documented sufficiently for me to get started! I'll try it out

**Comment by chrisjsewell** [comment]
> I love to see it is documented sufficiently for me to get started

no point having a tool that no one can use 😉
leave any feedback in https://github.com/executablebooks/rst-to-myst/issues/5 cheers

**Comment by consideRatio** [comment]
@chrisjsewell thank you for your amazing work in executablebooks! :heart:

**Comment by consideRatio** [comment]
Self merging this docs only PR as I want to keep working on docs in general and will run into conflicts by not merging it at this point.

**Pull request merged**
