### PR TITLE
Updating sphinx_copybutton import

### PR DESCRIPTION
**Pull request by choldgraf**
Going to self-merge this since the docs will be broken until it's updated!

### CODE REVIEW

**Comment by choldgraf** [comment]
hmmm I have a feeling these errors are not related to this PR...

**Comment by consideRatio** [comment]
Nope =/ Seems like a bunch of network errors in general. Perhaps travis network connection is in bad shape? If not, what can we have done?

**Comment by consideRatio** [comment]
https://www.traviscistatus.com/

**Comment by choldgraf** [comment]
arg!

**Pull request merged**
