### PR TITLE
Add documentation to create a Kubernetes cluster on OVH

### LINKED ISSUE #1703: Documentation to create a Kubernetes cluster on OVH
### Proposed change

It would be nice to have documentation to create a Kubernetes cluster on OVH, so it can be listed next to the other cloud providers:

image

### Who would use this feature?

People who want to deploy on OVH.

### (Optional): Suggest a solution

It will probably be quite short (like the other sections), with screenshots to show parts of the UI.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #1703.

image

### CODE REVIEW

**Comment by jtpio** [comment]
cc @jagwar and @mael-le-gal if you want to have a look :)

**Comment by betatim** [comment]
ping  @jagwar and @mael-le-gal

**Comment by mael-le-gal** [comment]
Hello guys,

Sorry I completely missed your first request for review. We have a big project landing in September and we have been in a bit of a rush lately.

Your documentation seems quite accurate, this is exactly how the current binder cluster was spawn on our side.

**Comment by minrk** [comment]
Thanks! I'm going to merge this as-is since it has a first-pass approval. We can always review and refine in the future.

**Pull request merged**
