### PR TITLE
add note about kubectl on azure cloud shell

### PR DESCRIPTION
**Pull request by shanamatthews**
Cloud shell already has kubectl installed and trying to install it within cloud shell will cause access denied errors.

### CODE REVIEW

**Comment by consideRatio** [comment]
@shanamatthews Thank you for contributing!! :heart:



I'm having a warm fuzzy feeling about open source community ^^

**Comment by choldgraf** [comment]
Woooooooo!

**Comment by shanamatthews** [comment]
Warm and fuzzy open source vibes right back at you!! ✨💖

**Comment by willingc** [comment]
Thanks @shanamatthews for the PR. Keep sending us any updates or info that needs clarification on Azure. :sunny:

**Pull request merged**
