### PR TITLE
Add info about using an existing data8 image

### PR DESCRIPTION
**Pull request by yuvipanda**
Needs much better wordsmithing, flow checking and hyperlinking

### CODE REVIEW

**Comment by choldgraf** [comment]
Want me to make edits to this PR, or open a diff one after merge?

**Comment by yuvipanda** [comment]
Please make edits :)

**Comment by choldgraf** [comment]
added some extra explanations etc

**Comment by choldgraf** [comment]
LMK if it looks good to you and we can merge

**Pull request merged**
