### PR TITLE
Fix capitalization in all JupyterHub mentions

### LINKED ISSUE #3: Do a spelling consistency check for JupyterHub
JupyterHub should have the 'H' in caps.

### PR DESCRIPTION
**Pull request by parente**
Except for command line uses of jupyterhub and URLs

Fixes #3

### CODE REVIEW

**Comment by choldgraf** [comment]
LGTM, I assume you did a `ctrl+f` to find all the instances?

**Comment by willingc** [comment]
@choldgraf Just an FYI, @parente is one of the most meticulous coders on the team. A pleasure to work with his PRs.

Thanks @parente 👍

**Comment by choldgraf** [comment]
Sounds good! Nice to meet you @parente

**Comment by parente** [comment]
Nice to meet you too @choldgraf. As always, @willingc is too kind in her introductions. (I used vim / instead of ctrl-f.) 🙊

**Pull request merged**
