### PR TITLE
Remove makefile

### PR DESCRIPTION
**Pull request by willingc**
@yuvipanda I see you bumped to rc2. Did you want to update the Makefile too?

### CODE REVIEW

**Comment by yuvipanda** [comment]
I'm actually tempted to remove the makefile. We don't actually use it anywhere, and build.py does all the work in our CI process.

**Comment by willingc** [comment]
Let's remove it.

**Comment by willingc** [comment]
I could push to this PR.

**Comment by yuvipanda** [comment]
w00t! ty, @willingc

**Pull request merged**
