### PR TITLE
[Part 13 of #758] Added `scheduling.userDummy`

### PR DESCRIPTION
**Pull request by consideRatio**
## Warning

Needs rebase before merge. The actual content of this PR is actually only the following commit.

- [**Added `scheduling.userDummy` option**](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/931/commits/6da28d6908ddcc656174f291aa954341112a1463)

---

## About

Read about it in schema.yaml.

### CODE REVIEW

**Comment by consideRatio** [comment]
It is to mimic a real user as compared to a placeholder that has lower priority. If we as developers or a person setting up autoscaling want to verify eviction logic works as intended, I think we should have this, if not sure lets delete it.

This could allow for quite simple automated tests that takes very short time to execute.

**Comment by minrk** [comment]
From my reading of #929, placeholders can be used to do the same thing. Is that not true?

**Comment by minrk** [comment]
I think it makes the most sense to move this to a documentation/example rather than a utility we deploy.

**Comment by consideRatio** [comment]
@minrk I think should be available as a zero replica controller, or dropped without regret entirely and only documented as a closed PR. Closing!

**Pull request closed without merging**
