### PR TITLE
Add badge to GitHub and link to issues

### LINKED ISSUE #30: add link to github repo on website
I think there should be an obvious link on the website to the repo / issue tracker so that people can leave feedback more easily.

### PR DESCRIPTION
**Pull request by willingc**
Closes #30

screen shot 2017-04-26 at 8 57 26 am

### CODE REVIEW

**Comment by choldgraf** [comment]
TBH I am not a huge fan of the "fork me on github" ribbon... I don't think it adheres to modern design principles for the web and is kinda confusing to new users who don't really know what it means.

BUT, I'm not blocking the PR on this or anything, I think it's definitely better than nothing :) just curious what the community feels about this. I do get a nice feeling of nostalgia from the ribbon!

**Comment by willingc** [comment]
@choldgraf I could go either way on the right hand side's "Fork me on GitHub". We don't have it enabled on other Jupyter docs. For consistency I'm going to remove. The more important part of the PR is links and badge in the left sidebar for the index page.

**Comment by choldgraf** [comment]
yes those are super helpful :) I'll merge after the next push!

**Comment by choldgraf** [comment]
Now I feel kind of bad for the ribbon haha...

Thanks @willingc :)

**Pull request merged**
