### PR TITLE
Add annotations to image puller pods

### LINKED ISSUE #1627: Annotate image puller and awaiter
### Proposed change
It is not possible to add annotation to the image puller deployments.

### Who would use this feature?
This is useful for example deploying jupyterhub to an istio enabled namespace (where all pods are auto injected unless they are annotated)

Happy to submit a PR on this.

### PR DESCRIPTION
**Pull request by duongnt**
This PR adds the ability to add annotations to the continuous and hook image puller pods.

Fixes #1627

### CODE REVIEW

**Comment by consideRatio** [comment]
Welcome and thanks for your PR @duongnt! I think this makes sense to add, could you do the following?

- [ ] Add a entry for `prePuller.annotations` set to `{}` in values.yaml. Just a practice we have, I find it useful to help myself track what is possible to configure, and I know `helm lint` likes it.
- [ ] Use `with` instead of `if`, use `trimSuffix "\n"`, and pipe into `toYaml` like below. This is just format nitpicking.

```yaml
      {{- with .Values.prePuller.annotations }}
      annotations:
        {{- . | toYaml | trimSuffix "\n" | nindent 8 }}
      {{- end }}
```

**Comment by duongnt** [comment]
@consideRatio Thanks for your review! I addressed your comments.

**Comment by duongnt** [comment]
Just realize that this fixes #1627

**Comment by consideRatio** [comment]
@duongnt I think you also need to not use a `"` when you reference `.Values...`. After that this PR is ready for merge I think!

**Comment by consideRatio** [comment]
Thank you @duongnt !!!!! :heart: :tada:

**Pull request merged**
