### PR TITLE
image-awaiter: fix known vulns. by updating to golang:1.17 in image build stage

### PR DESCRIPTION
**Pull request by nreith**
Update to golang:1.17 base image to patch 1 critical and 5 high vulnerabilities

image

### CODE REVIEW

**Comment by nreith** [comment]
Team, I'm new to contributing here and in open source in general. Please let me know if I've staged the MR wrong, and how to handle tags and other aspects. Thanks.

**Comment by consideRatio** [comment]
Nice thank you @nreith! I appreciate that you are providing the report of vulnerabilities as well! This LGTM! ❤️ 🎉 🚀 🌻 

Btw, what GitLab calls merge requests (MR) are on GitHub called pull requests (PR). Ill update the title to reflect this relates to the image-awaiter image to help people scope what its about on a high level.

**Comment by nreith** [comment]
Thanks @consideRatio ! My first open-source contribution. Hopefully many more to come. :-)

**Comment by consideRatio** [comment]
:heart: :tada: @nreith welcome to the Jupyter open-source community and the larger community of open source in general :)

**Pull request merged**
