### PR TITLE
custos-oauthenticator-requirement

### PR DESCRIPTION
**Pull request by isururanawaka**
Custos is a security middleware for science gateways. See https://airavata.apache.org/custos/ for additional information.

This PR contains the dependency for the implementation of Custos Authenticator for Jupyterhub as an OIDC plugin.

### CODE REVIEW

**Comment by consideRatio** [comment]
I want to raise this for discussion with the @jupyterhub/jupyterhubteam. What policy should we have for adding an authenticator to the jupyterhub image used in this Helm chart?

Currently, we have the following:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/2d03a133eb2253e25891f3bbd59f9124cfdbdde6/images/hub/requirements.in#L10-L18

I'm thinking we should stick to those maintained by the JupyterHub team, and ask that other third party authenticators are installed by deriving a custom image or similar.

**Comment by manics** [comment]
By including a package in Z2JH we're saying it works, it's safe, and it's secure. I think sticking with just JupyterHub authenticators is the most practical solution. 

_If_ we wanted to relax it slightly we could add authenticators where there's strong demand, and evidence of long term support for the package.

I think adding more docs on extending the hub image including a basic example would be nice to have though, and provides a page we can point people to if this comes up again.

**Comment by willingc** [comment]
I believe that we should only include JupyterHub packages in the chart. For cases like this particular one (thanks @isururanawaka for the suggestion), I would prefer creating a page in the docs or wiki for external packages. IIRC we had a section in the JupyterHub docs for Community Provided Packages.

**Comment by smarru** [comment]
@consideRatio @manics @willingc thanks if it helps, we are committed to supporting this authenticator. Custos is part of Apache Airavata, a top-level Apache Software Foundation project - https://airavata.apache.org/custos/ and is supported by NSF - https://www.nsf.gov/awardsearch/showAward?AWD_ID=1840003 our goal for this PR is for any users of the Jetstream cloud to checkout the code and have native support of federated authentication using CILogon for US research community - https://jetstream-cloud.org/

**Comment by isururanawaka** [comment]
@manics Thanks for the suggestions. We will update the source and README file.

**Comment by consideRatio** [comment]
Thanks for the discussion everyone, and thank you for your work to provide an authenticator for the community to use @isururanawaka!

I'll go ahead and close this PR as there seem to be agreement that we would like to stick to only having JupyterHub maintained authenticator packages in this image.

We currently have no great option on how to install an additional package on startup by adding some configuration or similar, but there is an open issue of relevance about it to keep an eye on: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2265.

**Pull request closed without merging**
