### PR TITLE
Use 'kind get kubeconfig' instead of deprecated 'kubeconfig-path'

### LINKED ISSUE #1650: [kind] ERROR: unknown flag: --name
### Bug description

Bootstrapping a development cluster with kind 0.7 fails with the following error:

```
`kind get kubeconfig-path --name jh-dev` errored (1)
ERROR: unknown flag: --name
```

### How to reproduce

1. Clone z2jh repo, branch master
2. Run `./dev kind create`

### Your personal set up

 - OS: MacOS, Docker Desktop
 
 - Version:
  - `kind v0.7.0 go1.13.6 darwin/amd64`
  - `docker 19.03.8`
 
 - Configuration: fresh checkout from master

### PR DESCRIPTION
**Pull request by stv0g**
`kind get kubeconfig-path` has been removed in https://github.com/kubernetes-sigs/kind/commit/e258374de80352325dd830b8e5faf9270567d1a2

The PR uses `kind get kubeconfig` and writes the contents into a local file.

Closes #1650

### CODE REVIEW

**Comment by stv0g** [comment]
Hi @manics,

I refactored the duplicated code into a new function as you proposed.

**Comment by consideRatio** [comment]
@stv0g thank you for your contribution and @manics for your review! :heart:

I've felt that the local development experience with this `dev` script and the way it use `kind` isn't good enough, and suggest we kill it entirely in favor of `k3s` (and optionally `k3d` which wraps k3s in docker containers).

In #1664 I'm removing the `dev` script and the use of `kind`. I created the `dev` script an feel it was a big failure because of how much complexity it added and how fragile it behaved. I hope that by killing it now rather than later I will spare others the time wasted on interacting with it.

With this considered, does it feel okay to close this PR @stv0g?

**Comment by stv0g** [comment]
@consideRatio I agree.

Are you planning to use the new dev setup also for CI tests?

I was trying to get the CI tests ready for IPv6. Unfortunately, kind's IPv6 support is broken :(

**Comment by consideRatio** [comment]
@stv0g yepp thats the plan - local dev + CI environment

**Comment by consideRatio** [comment]
Seems like bleeding edge support for it at best: https://github.com/rancher/k3s/issues/284

**Comment by stv0g** [comment]
At least the Rancher UI is not capable of IPv6 :(

**Comment by consideRatio** [comment]
@stv0g I hope to be able to help you help everyone with the IPv6 support, I'm slowly catching up with a backlog of things to do.

**Comment by consideRatio** [comment]
We have now replaced `kind` entirely with `k3s` in our CI setup, and the local dev setup instructions are updated to use `k3s` or `k3d`.

**Pull request closed without merging**
